# Generated by Django 4.2.27 on 2026-02-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField(db_index=True, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('raw_text', models.TextField()),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('appliance_type', models.CharField(blank=True, max_length=100)),
                ('issue_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Group Message / Lead',
                'verbose_name_plural': 'Group Messages / Leads',
                'ordering': ['-created_at'],
            },
        ),
    ]
