# Generated by Django 4.2.27 on 2026-02-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_message_id', models.BigIntegerField(db_index=True, unique=True)),
                ('chat_id', models.BigIntegerField(db_index=True)),
                ('sender_username', models.CharField(blank=True, max_length=100)),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('raw_text', models.TextField()),
                ('mount_type', models.CharField(blank=True, max_length=200)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('purchase_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
    ]
